---
title: "MPIPE"
format: html
editor: source
---

# Load dependancies

```{r, include=F}
# knitr::opts_chunk$set(echo = FALSE)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) # Set working directory to the current file
rm(list = ls())

options(rstudio.help.showDataPreview = FALSE)
MPath <- "./src/CRB-MARSHAL/"

libs <- c("fmsb", 
          "SciViews", 
          "pander", 
          "visreg", 
          "readxl", 
          "EnvStats", 
          "FactoMineR", 
          "factoextra", 
          "knitr", 
          "data.table", 
          "reticulate", 
          "xml2", 
          "tidyverse", 
          "dplyr", 
          "viridis", 
          "Hmisc", 
          "ggplot2", 
          "gridExtra", 
          # "outliers",
          "Matrix", 
          "emmeans")

for(pk in libs) {
  library(pk, character.only = T)
}

# source(paste0(MPath,"io_function.R")) # CROOTBOX
source(paste0(MPath, "Get_SUF.R")) # MARSHAL
source(paste0(MPath, "SUF.R"))
source(paste0(MPath, "CRBM_functions.R"))

TRoot_path <- "./src/FUNCTIONS/T-Root/"
for (i in list.files(TRoot_path, pattern = ".R")) {
  print(i)
  source(paste0(TRoot_path, i))
}
```

# Pipeline to run MARSHAL

## Create database tables

```{r}
# # SCENARIOS
# Scenarios.IDs <- e(Scenario_id = c("test"), SG = c(F), EndoSub = F, ExoSub = F, EndoCS = F)
# write.csv(Scenarios.IDs, "CRB-MARSHAL/inputs/Scenarios_ID.csv", row.names = F)
# 
# # RSA
# RSA_list <- list.files("CRB-MARSHAL/inputs/RSA/", pattern = ".csv")
# RSA.IDs <- tibble(planttype = "Tomato", age = 30, rep = 1:10) %>% mutate(RSA_id = paste0(planttype, "_", age, "_", rep))
# write.csv(RSA.IDs, "CRB-MARSHAL/inputs/RSA_ID.csv", row.names = F)
# 
# # RSHA
# RSHA.IDs <- tibble(RSHA_id = c(), age = c(), Scenario_id = c(), RSA_id = c())
# write.csv(RSHA.IDs, "CRB-MARSHAL/inputs/RSHA_ID.csv", row.names = F)
```

## Load DB tables and RSA

```{r}
Scenarios.IDs <- read.csv(paste0(MPath, "inputs/Scenarios_ID.csv"))
RSA.IDs <- read.csv(paste0(MPath, "inputs/RSA_ID.csv"))
# RSHA.IDs <- read.csv("CRB-MARSHAL/inputs/RSHA_ID.csv")

RSA_list <- RSA.IDs$RSA_id[1] # Implement a way to select RSA_ids

# LOAD RSA FILES AND CREATE A META FILE
RSA.all      <- tibble()
for(RSA_id in RSA_list){
  RSAi        <- read.csv(paste0(MPath, "inputs/RSA/", RSA_id, ".csv"))
  RSAi$RSA_id <- RSA_id
  RSA.all     <- rbind(RSA.all, RSAi)
}
```

## Define example scenario

kr_reg and kx_reg function (TO DEVELOP)

```{r}
kr_reg <- function(x, timing){
  if(x <= timing[1]){
    kr <- 4.11e-8
  }else if(x > timing[1] & x <= timing[2]){
    kr <- 6.4e-8
  }else if(x > timing[2]){
    kr <- 8.4e-8
  }
  return(kr)
}

kx_reg <- function(x, timing){
  if(x <= timing[1]){
    kx <- 2.07e-11
  }else if(x > timing[1] & x <= timing[2]){
    kx <- 1e-9
  }else if(x > timing[2]){
    kx <- 1.2e-8
  }
  return(kx)
}
```


```{r}
Scenario_id  <- "no_sub"

# Generate conds filte
conds.test <- create.conds(xmax = 40, timing1 = 7, timing2 = 20, SG = T)
conds.test$y[conds.test$type == "kr" & conds.test$x >= 7] <- 1.8e-5
```

## Load pre-computed scenarios

```{r}
conv_kr <- 0.001157407
conv_kx <- 1.157407e-09

Conds_1A <- read.csv("./Data/conds_scenarios/1A.csv")
Conds_1B <- read.csv("./Data/conds_scenarios/1B.csv")
Conds_2 <- read.csv("./Data/conds_scenarios/2.csv")
Conds_3 <- read.csv("./Data/conds_scenarios/3.csv")

# Convert m[4]*s-1*MPa-1 back to cm[4]*d-1*HPa-1
df <- Conds_1A
df$kr <- df$kr/conv_kr
df$Kx <- df$Kx/conv_kx
```

```{r}
# Define root orders
order_id = c(1,2,3)
order = c("Taproot", "Lateral", "LongLateral")
orders_df            <- tibble(order_id, order)

# Create Conds.conv
Conds.conv           <- df[c("x", "kr", "Kx")] 
colnames(Conds.conv) <- c("x", "kr", "kx")
Conds.conv           <- Conds.conv %>% gather(kr, kx, key = "type", value = "y")
Conds.conv           <- merge(Conds.conv, orders_df)
Conds.conv$id        <- seq(1, nrow(Conds.conv))
Conds.conv           <- Conds.conv[c("order_id", "order", "x", "type", "y", "id")]

# Add a zero x
Conds.conv           <- rbind(Conds.conv, Conds.conv %>% filter(x == 1) %>% mutate(x = 0))
```

## Loop MARSHAL

```{r, include = F}
conds <- Conds.conv
Scenario_id <- "Scenario_1A"
path.out <- paste0(MPath, "outputs/", Scenario_id, "/")

# Create folder for the Scenario
if(dir.exists(path.out)){
  unlink(paste0(path.out, "*"), recursive = F)
}else{
  dir.create(path.out)
}

# MARSHAL PARAMETERS
# conds        <- read.csv("CRB-MARSHAL/inputs/conductivities3.csv")
soil         <- read.csv(paste0(MPath, "inputs/soil.csv"))

# ============================================================================ #
results <- run.MARSHAL.loop(RSA_list, RSA.all, 
                            Scenario_id = Scenario_id, 
                            conds, 
                            soil, 
                            tmin = 1, tmax = 30, step = 0.25,       # Decomposition of RSA timing 
                            timing1 = 7, timing2 = 20)           # SG timing
# ============================================================================ #

RSHA.all <- results$RSHA.all
Macro.all <- results$Macro.all

write.csv(RSHA.all, paste0(path.out, "RSHA_all.csv"), row.names = F)
write.csv(Macro.all, paste0(path.out, "Macro_all.csv"), row.names = F)
```

Check SUF

```{r}
ggplot(RSHA.all %>% filter(RSHA_id == RSHA.all$RSHA_id[-1])) +
  geom_point(aes(x = time, y = SUF, color = as.factor(branchID))) 
```


Make plots

```{r}
source("./src/CRB-MARSHAL/CRBM_functions.R")
Scenario_id <- "Scenario_1A"
path.out <- paste0(MPath, "outputs/", Scenario_id, "/")

RSHA.all <- read.csv(paste0(path.out, "RSHA_all.csv"))
Macro.all <- read.csv(paste0(path.out, "Macro_all.csv"))

plot.path <- paste0(path.out, "plots/")


# Create folder for the Scenario
if(dir.exists(plot.path)){
  unlink(paste0(plot.path, "*"), recursive = F)
}else{
  dir.create(plot.path)
}

unlink(paste0(plot.path, "*"), recursive = F)

for(ti in unique(RSHA.all$age)){
  cat("ti : ", format(round(ti, 2), nsmall = 2), "\n")
  plot.CRBM(RSHA.all, Macro.all, ti, path.plot = plot.path, Krs.max = max(Macro.all$Krs))
}
```

```{r}
library(magick)
img <- list.files(plot.path, pattern = ".png")
img_list     <- lapply(paste0(plot.path, img), image_read)
img_join     <- image_join(img_list)
img_animated <- image_animate(img_join, delay = 10)
  
image_write(image = img_animated,
            path = paste0(path.out, "animated.gif"))
```


