reconnect.nodes <- function(all_roots){
  # Reconnect nodes of a RSA
  
  all_roots <- all_roots%>%arrange(time)
  all_roots <- all_roots%>%dplyr::mutate(length = sqrt((x1-x2)^2+(y1-y2)^2+(z1-z2)^2))
  all_roots$node2ID <- 1:nrow(all_roots)
  all_roots$node1ID[all_roots$branchID == 1][1] <- 0
  all_roots$node1ID[all_roots$branchID == 1][-1] <- which(all_roots$branchID == 1)[-length(which(all_roots$branchID == 1))] # tap root ordination
  
  for(i in unique(all_roots$branchID)[-1]){
    all_roots$node1ID[all_roots$branchID == i][-1] <- which(all_roots$branchID == i)[-length(which(all_roots$branchID == 1))]
    if(all_roots$type[all_roots$branchID == i][1] %in% c(4,5)){ # connection with the collar
      all_roots$node1ID[all_roots$branchID == i][1] <- 0
    }
    if(all_roots$type[all_roots$branchID == i][1] %in% c(2,3)){ # connection with the parental root
      x1_child <- all_roots$x1[all_roots$branchID == i][1]
      y1_child <- all_roots$y1[all_roots$branchID == i][1]
      z1_child <- all_roots$z1[all_roots$branchID == i][1]
      tmp_time <- all_roots$time[all_roots$branchID == i][1]
      nearest <- all_roots%>%filter(branchID != i)%>%
        mutate(euc = sqrt((x1-x1_child)^2+ (y1 - y1_child)^2 + (z1 - z1_child)^2))
      nearest <- nearest[nearest$euc == min(nearest$euc), ]
      all_roots$node1ID[all_roots$branchID == i][1] <- nearest$node2ID[1] # oldest segments
    }
  }
  oups <- which(all_roots$node1ID == all_roots$node2ID)
  if(length(oups) > 0){
    for(o in oups){
      self_seg_age <- all_roots$time[all_roots$node2ID == o][1]
      self_seg_id <- all_roots$branchID[all_roots$node2ID == o][1]
      nearest <- all_roots%>%filter(branchID == self_seg_id, time < self_seg_age)
      all_roots$node1ID[all_roots$node2ID == o][1] <- nearest$node2ID[nearest$time == max(nearest$time)]
    }
  }
  return(all_roots)
}

# ==============================================================================

run.MARSHAL.loop <- function(RSA.all,
                             Sim_ID,
                             conds, 
                             soil,
                             SG_timing,
                             hetero = F,
                             Psi_collar = -15000,
                             tmin = 1,
                             tmax = 30,
                             step = 1,
                             radius.min = 0.198,
                             radius.max = 1
                             ){
  
  #' @description
    #' function to run MARSHAL on a list of Root System Architectures, for a given set of Conductivities and parameters.
    #' For each RSA, for each timestep between tmin and tmax, it will subset the corresponding RSA and compute MARSHAL.
  #' @param RSA.all A dataframe containing RSA data generated by CRootBox, with and additional column RSA_id that identifies unique RSA.
  #' @param conds A dataframe containing local root hydraulic properties to give to MARSHAL. Should contain columns "order_id", "order", "x", "type", "y", "id".
  #' @param soil A dataframe containing soil properties to give to MARSHA. Should contain columns "id", "z", "psi".
  #' @param SG_timing A vector of 2 values. The first corresponds to a shift in anatomy, the second the expension of Secondary Growth.
  #' @param hetero Boolean. Set true to have heterogenous soil properties.
  #' @param Psi_collar Boundary condition of collar water potential. Default value is -15000.
  #' @param tmin Minimum age of simulation
  #' @param tmax Maximum age of simulation
  #' @param step Timestep 
  #' @param radius.min Minimum radius of roots
  #' @param radius.max Maximum radius of roots
  
  # INITIATE DFs
  RSHA.all     <- tibble()
  Macro.all    <- tibble()
  
  # ========================================================================== #
  # LOOP MARSHAL FOR TIMESTEPS
  for(ti in seq(tmin, tmax, by = step)){
    
    # Subset RSA corresponding to timestep
    cat("Subsetting RSA...  \n")
    RSA.all.ti     <- RSA.all %>% filter(time <= ti)
    RSA.all.ti$age <- (ti - RSA.all.ti$time)
    
    # UPDATE RADIUS
    cat("Updating radius... \n")
    RSA.all.ti$radius <- radius_pred(newdata = RSA.all.ti, radius_lm = lm_r)
    RSA.all.ti$radius[RSA.all.ti$radius < rmin]                <- radius.min
    RSA.all.ti$radius[RSA.all.ti$radius > rmax]                <- radius.max
    RSA.all.ti$radius[which(is.na(RSA.all.ti$radius))]         <- radius.max
    
    # ======================================================================== #
    # LOOP FOR EACH RSA_ID
    for(RSA_id_i in unique(RSA.all.ti$RSA_id)){
      
      # Select the corresponding RSA
      RSA_temp  <- RSA.all.ti %>% filter(RSA_id == RSA_id_i)
      
      # Create RSHA_id_i as combination of RSA_id and Timestep
      RSHA_id_i <- paste0(RSA_id_i, "_", ti, "_", Sim_ID)
      cat("t : ", ti, " | RSHA_id_i : ", RSHA_id_i, "\n")
      flush.console()
      
      # RECONNECT NODES
      RSA_temp <- suppressWarnings(reconnect.nodes(RSA_temp))
      
      
      try({
        # ----------------------------------------------- #
        Marshal_temp <- getSUF(table_data  = RSA_temp,
                               table_cond  = conds,
                               table_soil  = soil,
                               hetero      = hetero, 
                               Psi_collar  = Psi_collar);
        # ----------------------------------------------- #
        
        # Create output files        
        RSHA_temp         <- Marshal_temp$root_system
        RSHA_temp$kr      <- Marshal_temp$kr
        RSHA_temp$kx      <- Marshal_temp$kx
        RSHA_temp$SUF     <- Marshal_temp$suf
        RSHA_temp$RSHA_id <- RSHA_id_i
        RSHA_temp$RSA_id  <- RSA_id_i
        RSHA_temp$age     <- ti
        
        # Create macro df
        Macro.temp <- tibble(tpot = Marshal_temp$tpot,
                             Krs = Marshal_temp$krs,
                             Krs_exact = Marshal_temp$krs_exact,
                             RSHA_id = RSHA_id_i,
                             RSA_id = RSA_id_i,
                             age = ti
        )
        
        # RBIND RSHA.all and Macro
        RSHA.all  <- rbind(RSHA.all, RSHA_temp)
        Macro.all <- rbind(Macro.all, Macro.temp)
        
      })
      
    }
  }
  
  return(list(RSHA.all  = RSHA.all, 
              Macro.all = Macro.all))
}

# ==============================================================================

plot.CRBM <- function(RSHA.all, Macro.all, ti, path.plot, Krs.max, radius.range = c(1, 3)){
  
  RSA_id_i       <- unique(RSHA.all$RSA_id)[1]
  
  data2plot      <- RSHA.all %>% filter(RSA_id == RSA_id_i  & age == ti)
  macro2plot_all <- Macro.all %>% filter(RSA_id == RSA_id_i)
  macro2plot_i   <- Macro.all %>% filter(RSA_id == RSA_id_i & age == ti)
  
  require(cowplot)
  # PLOT ALL
  # ========================================================================== #
  p_kr <- ggplot(data2plot) + 
    
    # Plot segments
    geom_segment(aes(x= x1, xend = x2, y = z1, yend = z2, 
                     color = kr, size = radius)) +
    
    # Set limits
    xlim(-15, 15) +
    ylim(round(min(RSHA.all$z1)), 0) +
    
    # Set radius
    scale_size_continuous(range = radius.range, 
                          limits = c(min(RSHA.all$radius), 
                                     max(RSHA.all$radius))
                          ) +
    
    # Set colors
    scale_color_viridis_c(option = "D", 
                          limits = c(min(RSHA.all$kr), 
                                     max(RSHA.all$kr))
                          ) +
    
    coord_fixed() +
    # facet_wrap(~RSA_id, nrow = 2) +
    # ggtitle(paste0("kr | time : ", ti)) +
    
    # ggtitle("Kr") +
    ggtitle(expression(k[r] ~ "[" ~ m ~ MPa^{-1} ~ s^{-1} ~ "]")) +
    
    theme_test()
  
  # ========================================================================== #
  p_kx <- ggplot(data2plot) +
    geom_segment(aes(x= x1, xend = x2, y = z1, yend = z2, 
                     color = kx, size = radius)) +
    xlim(-15, 15) +
    ylim(round(min(RSHA.all$z1)), 0) +
    
    scale_size_continuous(range = radius.range,
                          limits = c(min(RSHA.all$radius), 
                                    max(RSHA.all$radius)
                                    )
                          ) +
    
    scale_color_viridis_c(option = "D", 
                          limits = c(min(RSHA.all$kx), 
                                     max(RSHA.all$kx)
                                     )
                          ) +
    coord_fixed() +
    # facet_wrap(~RSA_id, nrow = 2) +
    # ggtitle(paste0("kx | time : ", ti)) +
    ggtitle(expression(k[x] ~ "[" ~ m^{4} ~ MPa^{-1} ~ s^{-1} ~ "]")) +
    theme_test()
  
  # ========================================================================== #
  p_suf <- ggplot(data2plot) +
    geom_segment(aes(x= x1, xend = x2, y = z1, yend = z2, 
                     color = SUF, size = radius)) +
    xlim(-15, 15) +
    ylim(round(min(RSHA.all$z1)), 0) +
    
    # Size of radius
    scale_size_continuous(range = radius.range, 
                          limits = c(min(RSHA.all$radius), 
                                     max(RSHA.all$radius))
                          ) +
    
    # Color of SUF
    scale_color_viridis_c(option = "magma",
                          breaks = c(min(data2plot$SUF), 
                                     max(data2plot$SUF)),
                          labels = c("low", "high"),
                          direction = 1
                          # , limits = c(0, max(RSHA.all$SUF[RSHA.all$RSA_id == RSA_id_i]))
                          ) +
    
    # Fix position of legends
    guides(
      color = guide_colorbar(order = 1),  # Color legend appears first
      size = guide_legend(order = 2)   # Size legend appears second
    ) +
    
    coord_fixed() +
    # facet_wrap(~RSA_id, nrow = 2) +
    # ggtitle(paste0("SUF | time : ", ti)) +
    
    theme_test() +
    # theme(legend.position = "none") +
    ggtitle("SUF [normalised]") 
  
  # ========================================================================== #
  p_krs <- ggplot() +
    geom_line(data = macro2plot_all, aes(x = age, y = Krs), size = 1) +
    geom_point(data = macro2plot_i, aes(x = age, y = Krs), size = 4, color = "red") +
    xlim(0, max(macro2plot_all$age)) +
    ylim(0, Krs.max) +
    ggtitle(expression(K[rs] ~ "[" ~ m^{3} ~ MPa^{-1} ~ s^{-1} ~ "]")) +
    theme_bw()
  
  # ========================================================================== #
  # MERGE ALL PLOTS
  title  <- ggdraw() + draw_label(paste0("Time : ", format(round(ti, 2), nsmall = 2)))
  p_full <- plot_grid(p_kr, p_kx, p_suf, p_krs, nrow = 2)
  p_full <- plot_grid(title, p_full, nrow = 2, rel_heights = (c(0.1, 0.7)))
  pfinal <- ggdraw(p_full) + theme(plot.background = element_rect(fill = "white"))
  
  ggsave(filename = paste0(path.plot, "Full", "_", sprintf("%04d", round(ti*100)), ".png"),
         plot = pfinal, device = "png", 
         width = 10, height = 10, 
         units = "in", dpi = 200
         )
}

# ==============================================================================
create.conds <- function(S_ID, 
                         nmin,
                         nmax, 
                         SG_timing, 
                         MS_timing,
                         radius_pred_f,
                         kr_pred, 
                         kx_pred,
                         rmin         = 0.1987, 
                         rmax         = 2,
                         kAQP_start   = 6.35e-7,
                         kAQP_end     = 6.35e-7,
                         kr.min       = 0, 
                         kr.max       = 1e-3,
                         kx.min       = 0,
                         kx.max       = 1
)
{
  
  conds.out         <- tibble(age          = seq(nmin,nmax),
                              S_ID         = S_ID,
                              radius       = 0,
                              Barrier_Name = 0,
                              kr           = 0,
                              kx           = 0,
                              kAQP         = 0)
  
  # Set Radius
  conds.out$radius                                  <- radius_pred(newdata = conds.out,
                                                                   radius_lm = radius_pred_f)
  conds.out$radius[conds.out$radius < rmin]         <- rmin
  conds.out$radius[conds.out$radius > rmax]         <- rmax
  conds.out$radius[which(is.na(conds.out$radius))]  <- rmax
  
  # Set Maturation Stages
  conds.out$Barrier_Name[conds.out$age <= MS_timing[1]]   <- "En.CS"
  conds.out$Barrier_Name[conds.out$age > MS_timing[1] & 
                         conds.out$age <= MS_timing[2]]   <- "En.CS-Ex.LC"
  conds.out$Barrier_Name[conds.out$age > MS_timing[2]]    <- "En.CS-Ex.Sub"
  
  # Set kAQP as linear function of kAQP_start and kAQP_end
  conds.out$kAQP <- kAQP_start + (conds.out$age * (kAQP_end - kAQP_start)/(max(conds.out$age) - min(conds.out$age)))
  
  # Set kr and kx
  conds.out$kr                        <- kr_pred(newdata = conds.out, lm_kr = lm_kr)
  conds.out$kr[conds.out$kr > kr.max] <- kr.max
  conds.out$kr[conds.out$kr < kr.min] <- kr.min
  conds.out$kr[which(is.na(conds.out$kr))]  <- kr.max
  
  conds.out$kx <- kx_pred(newdata = conds.out, lm_kx = lm_kx)
  conds.out$kx[conds.out$kx > kx.max] <- kx.max
  conds.out$kx[conds.out$kx < kx.min] <- kx.min
  conds.out$kx[which(is.na(conds.out$kx))]  <- kr.max
  
  # # Gather
  # conds.out <- conds.out %>% gather(radius, kAQP, kr, kx, 
  #                                   key = "type", value = "y")
  
  return(conds.out)
}


