#!/bin/sh 
#SBATCH --job-name=Job_9      # Job name 

#SBATCH --ntasks=1                    # Run on a single CPU 

#SBATCH --mem=15gb                     # Memory limit 

#SBATCH --output=my_job_9.out    # Standard output and error log 

#SBATCH --time=30:00:00               # Time limit hrs:min:sec 

#SBATCH --output=results/my_job_9.out    # Standard output and error logZ 

#SBATCH --partition=Def 

#
#
#
JOB_DIR=$HOME/GRANAR_MECHA_CECI/
SRC_DIR=$HOME/GRANAR_MECHA_CECI/
DST_DIR=$HOME/GRANAR_MECHA_CECI/results/
TMP_DIR=$GLOBALSCRATCH/users/temp_9
#
#
cd $JOB_DIR                             # Set directory to home
if [ ! -d $TMP_DIR ]; then           # If TMP_DIR folder do not exist ;
echo $PWD
echo Making TMP_DIR = $TMP_DIR
mkdir -p $TMP_DIR                    # We create a folder called TMP_DIR
fi
cp -R $SRC_DIR/* $TMP_DIR            # We copy SRC_DIR into TMP_DIR
cd $TMP_DIR/                         # We set the new TMP_DIR as directory
#
echo $PWD
#
# Start simulations
module load R
Rscript $SRC_DIR/Job_M_9.R
#
#Done with simulations
touch $DST_DIR/Done_9.txt
# Finish processing and copy results to user directory
#
# Copy all individual output files with the (numerical) order they belong
cp -r $TMP_DIR/results/ $DST_DIR
cd $DST_DIR   # go back to DST folder
rm -rf $TMP_DIR  # delete TMP_DIR
