# Packages
library(readxl)
# library(pander)
# library(car)
library(EnvStats)
# library(emmeans)
# library(visreg)
library(FactoMineR)
# library(factoextra)
library(knitr)
# library(epitools)
# library(corrplot)
# library(NbClust)
# library(pastecs)
library(data.table)
# library(ggpubr)
library(reticulate)
library(xml2)
library(tidyverse)
library(plyr)
library(deldir)
library(viridis)
# library(cowplot)
library(Hmisc)
library(devtools)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(sp)

# library(ggradar)
# library(fmsb)
library("packcircles")
# library("alphahull")
library(purrr)
library(maptools)
library(sp)
library(geometry)
library(rgl)
library(stats)
# library(rgeos)
# library("SciViews")
# library(sjPlot)

# library(extrafont)
# library(hrbrthemes)
# library(kohonen)
# library(retistruct)